Refactor: Cascader
youzan/zent pull request #1376
Opened 2020-04-17 07:21 UTC by liaoyu

- 将 Cascader 抽成两个独立的组件 MenuCascader、TabsCascader
- MenuCascader 支持多选、搜索、滚动加载

2020-08-17 06:28 UTC, cpylua commented on packages/zent/src/cascader/TabsCascader.tsx
> +            loadingStage: -1, // 标识取消 loading 状态
`-1` 是个特殊标识？

2020-08-17 06:29 UTC, cpylua commented on packages/zent/src/cascader/TabsCascader.tsx
> +    );
`Popover` 放这里

2020-08-17 06:30 UTC, cpylua commented on packages/zent/src/cascader/TabsCascader.tsx
> +      });
`Object.assign` 和 `...newState` 重复了

2020-08-17 06:32 UTC, cpylua commented on packages/zent/src/cascader/TabsCascader.tsx
> +    const nextStage = stage + 1;
这个组件不支持异步数据加载？

2020-08-17 06:33 UTC, cpylua commented on packages/zent/src/cascader/components/SearchContent.tsx
> +              key={index}
`key` 最好别用 `index`

2020-08-17 06:36 UTC, cpylua commented on packages/zent/src/cascader/components/TabsContent.tsx
> +    const iteratorSum = hasValue ? value.length : 0;
变量名为啥叫 `iteratorSum`

2020-08-17 06:38 UTC, cpylua commented on packages/zent/src/cascader/components/TabsContent.tsx
> +            key={tabIndex}
`key` 最好不要用数组下标

2020-08-17 06:41 UTC, cpylua commented on packages/zent/src/cascader/components/MenuContent.tsx
> +      ></Checkbox>
简写

2020-08-17 06:45 UTC, cpylua commented on packages/zent/src/cascader/components/MenuContent.tsx
> +    parent: ICascaderItem | null
这里的父元素指什么？

2020-08-21 03:23 UTC, liaoyu commented on packages/zent/src/cascader/README_zh-CN.md
> +| displayRender | 选择后展示的渲染函数 | `selectedOptions =>  selectedOptions.map(option => option.label).join(' / ')` | '' |
重命名为 renderValue 了

2020-08-21 03:23 UTC, liaoyu commented on packages/zent/src/cascader/README_zh-CN.md
> +| async | 是否异步搜索 | boolean | `false` | `true` |
异步搜索是用的 loadOptions

2020-08-21 03:24 UTC, liaoyu commented on packages/zent/src/cascader/README_zh-CN.md
> +| disabled | 是否禁用 | boolean | `false` | `true` |
做了兼容

2020-08-21 03:28 UTC, liaoyu commented on packages/zent/src/cascader/README_zh-CN.md
> +- 参数 `hasMore` 与 `scrollable` 配合时可判断它的子节点是否可滚动加载
要判断某一层级滚动加载是否还有数据，判断依据是父节点的 hasMore 属性。第一层级的节点由于没有父节点，调用 loadOptions 返回的 true or false 之后在组件内部维护是否可继续滚动加载

2020-08-21 03:31 UTC, liaoyu commented on packages/zent/src/popover/placement/top-left-sticky.ts
> + */
默认跟 TopLeft 一致，当会超出页面的右边界时，与右边界平行再往左平移

2020-08-21 03:31 UTC, liaoyu commented on packages/zent/src/popover/placement/top-left-sticky.ts
> +    },
会超出时与右边界平行

2020-08-21 03:32 UTC, liaoyu commented on packages/zent/src/popover/placement/auto-bottom-left-sticky.ts
> +import getViewportSize from '../../utils/dom/getViewportSize';
默认跟 auto-bottom-left 行为一致，当会超出页面的右边界时，与右边界平行再往左平移

2020-08-21 03:37 UTC, liaoyu commented on packages/zent/src/cascader/types.ts
> +  ) => Promise<ICascaderSearchItem[] | void | boolean>;
- `CascaderSearchItem[]` 是异步搜索的情况，只返回一部分数据
- void 是某一个节点加载它子节点数据的场景，业务方维护 options
- boolean 是滚动加载的场景，判断是否还有更多数据

2020-08-21 03:38 UTC, liaoyu commented on packages/zent/src/cascader/types.ts
> +  ) => Promise<void>;
城市级联只有加载子级数据的场景，无滚动加载及异步搜索

2020-08-21 03:39 UTC, liaoyu commented on packages/zent/src/cascader/types.ts
> +) => Promise<unknown>;
返回值改成了 void，不需要返回值

2020-08-21 03:39 UTC, liaoyu commented on packages/zent/src/cascader/types.ts
> +  stage: number
重命名为 level 了，表示当前是哪一层级，从 1 开始计数

2020-08-21 03:40 UTC, liaoyu commented on packages/zent/src/cascader/types.ts
> +  action: 'next' | 'scroll' | 'search';
加载下一层级

2020-08-21 03:42 UTC, liaoyu commented on packages/zent/src/cascader/trigger/Search.tsx
> +      />
这里不需要边框，只需要输入部分，使用 Input 组件要重写的样式比较多

2020-08-21 03:42 UTC, liaoyu commented on packages/zent/src/cascader/trigger/Tags.tsx
> +export default TagsTrigger;
已抽成独立组件

2020-08-21 03:44 UTC, liaoyu commented on packages/zent/src/cascader/trigger/Tags.tsx
> +            onRemove(item[item.length - 1], false);
在多选的场景下，删除一项跟取消勾选叶子节点的选中状态一个含义

2020-08-21 03:46 UTC, liaoyu commented on packages/zent/src/cascader/trigger/Tags.tsx
> +        key={item.map(li => li.value).join('-')}
已换成 FC，组件本身已经使用 React.memo 包裹

2020-08-21 03:47 UTC, liaoyu commented on packages/zent/src/cascader/trigger/index.tsx
> +          ref={this.elementRef}
冗余代码，已经移除

2020-08-21 03:49 UTC, liaoyu commented on packages/zent/src/cascader/trigger/index.tsx
> +    }
- 无搜索内容的时候，关闭 popover，清空组件的 value 值
- 有搜索内容的时候，只清空搜索内容

2020-08-21 03:50 UTC, liaoyu commented on packages/zent/src/cascader/common/constants.ts
> +    selectedOptions.map(it => it.label).join(' / '),
已 memo， 是 immutable 的

2020-08-21 03:51 UTC, liaoyu commented on packages/zent/src/cascader/common/constants.ts
> +export const commonProps = {
已补全

2020-08-21 03:54 UTC, liaoyu commented on packages/zent/src/cascader/common/utils.ts
> +  sum: ICascaderItem[] = []
一个临时变量，将树形结构打平的时候，需要记住前置的路径，比如遍历到了第三层级，sum = [ItemA, ItemB]

2020-08-21 03:56 UTC, liaoyu commented on packages/zent/src/cascader/common/utils.ts
> +  return traverseTree4CheckedOptions(tree);
更新树形节点的选中状态时，需要重新计算取到 cascader 的所有选中值，最终在 trigger 里显示出来

2020-08-21 03:56 UTC, liaoyu commented on packages/zent/assets/cascader.scss
> +      }
是写错了

2020-08-21 03:57 UTC, liaoyu commented on packages/zent/assets/cascader.scss
> +          max-width: 82%;
已使用 flex 换了写法

2020-08-21 03:57 UTC, liaoyu commented on packages/zent/assets/cascader.scss
> +          max-width: 82%;
这部分代码移除了

2020-08-21 03:59 UTC, liaoyu commented on packages/zent/src/cascader/TabsCascader.tsx
> +            loadingStage: -1, // 标识取消 loading 状态
是个特殊标识，换成了 null

2020-08-21 03:59 UTC, liaoyu commented on packages/zent/src/cascader/components/MenuContent.tsx
> +    parent: ICascaderItem | null
叶子节点的父节点

2020-08-25 02:31 UTC, liaoyu commented on packages/zent/src/cascader/MenuCascader.tsx
> +      }
已调整到搜索的时候计算

2020-08-26 04:11 UTC, cpylua requested changes
placement 改一下名字

2020-08-26 04:11 UTC, cpylua commented on packages/zent/src/cascader/components/SearchContent.tsx
> +  popover: Popover;
只传关闭弹层的函数就够了，不要传 `Popover`

2020-08-27 08:55 UTC, cpylua commented on packages/zent/src/cascader/common/utils.ts
> +  }
放外面，不要 export 就行了。

2020-08-27 08:57 UTC, cpylua requested changes

2020-08-27 08:57 UTC, cpylua commented on packages/zent/src/cascader/common/utils.ts
> +  }
放外面，不要 export 就行了。

2020-09-10 10:12 UTC, cpylua approved these changes

2020-09-10 12:50 UTC, merged