[new component]: Drawer
youzan/zent pull request #1466
Opened 2020-09-04 09:09 UTC by niuniu384665340

[new feature] Drawer: 新增Drawer组件及api文档

2020-09-08 09:03 UTC, niuniu384665340 commented on packages/zent/src/drawer/README_zh-CN.md
> +| closeBtn     | 自定义关闭按钮                                   | `ReactNode`                            | `true`  | 否       |
设置visible为false，会卸载组件

2020-09-08 09:04 UTC, niuniu384665340 commented on packages/zent/src/drawer/README_zh-CN.md
> +| closeBtn     | 自定义关闭按钮                                   | `ReactNode`                            | `true`  | 否       |
fix

2020-09-18 06:15 UTC, cpylua requested changes

2020-09-18 06:15 UTC, cpylua commented on packages/zent/assets/drawer.scss
> +$drawer-ease-out: cubic-bezier(0, 0, 0.58, 1);
用统一的 https://github.com/youzan/zent/blob/master/packages/zent/assets/theme/_timing-functions.scss

2020-09-18 06:15 UTC, cpylua commented on packages/zent/assets/drawer.scss
> +    z-index: 1050;
想清楚和 `Dialog` 哪个在前，不要用和 `Dialog` 一样的值

https://youzan.github.io/zent/zh/guides/contribute#guan-yu-z-index
https://github.com/youzan/zent/blob/master/packages/zent/assets/dialog.scss

2020-09-18 06:15 UTC, cpylua commented on packages/zent/assets/drawer.scss
> +    z-index: 1051;
同上z-index

2020-09-18 06:15 UTC, cpylua commented on packages/zent/assets/drawer.scss
> +  &-backdrop {
backdrop 用 portal 的

2020-09-18 06:15 UTC, cpylua commented on packages/zent/assets/drawer.scss
> +      }
用统一的，https://github.com/youzan/zent/blob/master/packages/zent/assets/theme/_default.scss

2020-10-16 09:25 UTC, niuniu384665340 commented on packages/zent/src/drawer/types.ts
> +    | React.MouseEvent<HTMLSpanElement, MouseEvent>
关闭弹窗回调方法，Portal组件、关闭按钮、遮罩都会触发

2020-10-16 09:28 UTC, niuniu384665340 commented on packages/zent/src/drawer/types.ts
> +  e:
目前是没啥用，先去掉了

2020-10-16 09:56 UTC, niuniu384665340 commented on packages/zent/src/drawer/demos/noMask.mdx
> +          setContent(false);
这个例子是演示无遮罩的场景，会在document上绑定原生click事件，e.stopPropagation只能阻止react合成事件，所以要用e.nativeEvent.stopImmediatePropagation

2020-10-16 09:57 UTC, niuniu384665340 commented on packages/zent/src/drawer/index.ts
> +export { default as useDrawerExiting } from './hooks/useDrawerExiting';
没场景 去掉了

2020-10-16 09:58 UTC, niuniu384665340 commented on packages/zent/src/drawer/components/DrawerContent.tsx
> +            e.nativeEvent.stopImmediatePropagation();
无遮罩的场景，会在document上绑定原生click事件，e.stopPropagation只能阻止react合成事件，所以要用e.nativeEvent.stopImmediatePropagation

2020-10-19 06:52 UTC, niuniu384665340 commented on packages/zent/assets/drawer.scss
> +    z-index: 1050;
drawer的二级弹窗会使用dialog，z-index应该比dialog低

2020-10-19 07:13 UTC, niuniu384665340 commented on packages/zent/assets/drawer.scss
> +  &-backdrop {
backdrop和drawer用的不同渐变效果，backdrop是透明度渐变，drawer是边缘滑出，得单独写个backdrop

2020-10-19 07:14 UTC, niuniu384665340 commented on packages/zent/src/drawer/Drawer.tsx
> +        />
backdrop和drawer用的不同渐变效果，backdrop是透明度渐变，drawer是边缘滑出，得单独写个backdrop

2020-10-20 09:52 UTC, cpylua commented on packages/zent/src/drawer/components/DrawerContent.tsx
> +            e.nativeEvent.stopImmediatePropagation();
考虑改成判断 `target` 是不是在内容区域内？

2020-10-21 06:24 UTC, cpylua requested changes
我记得你有个 demo 里还有 `stopImmediatePropagation` 的使用，那里可以删掉吗？

2020-10-21 06:24 UTC, cpylua commented on packages/zent/src/drawer/types.ts
>    | {
这里是不是多了个 `|` 看着好奇怪

2020-10-21 06:24 UTC, cpylua commented on packages/zent/src/drawer/types.ts
>  export type DrawerPropsType = (
你拆成两个 `interface` 吧，看着清楚些。

```ts
interface IDrawerCommonProps {
    onClose?: () => void; // 关闭drawer的回调
    className?: string; // 对话框外层容器的类名
    visible?: boolean; // Drawer是否可见
    maskClosable?: boolean; // 点击遮罩触发onClose
    closeOnESC?: boolean; // 按下 ESC 键时触发onClose
    mask?: boolean; // 是否显示遮罩
    title?: string; // 自定义头部内容
    footer?: string; // 自定义底部内容
    closeBtn?: string; // 自定义关闭按钮
}

interface IHorizontalDrawerProps extends IDrawerCommonProps {
    width?: string | number;
    placement: 'left' | 'right';
}

interface IVerticalDrawerProps extends IDrawerCommonProps {
    height?: string | number;
    placement: 'top' | 'bottom';
}

type DrawProps = IHorizontalDrawerProps | IVerticalDrawerProps;
```

2020-10-21 06:24 UTC, cpylua commented on packages/zent/src/drawer/types.ts
> +  height: string | number;
`IDrawerContent` 也和 `DrawerProps` 一样拆开

2020-10-21 06:24 UTC, cpylua commented on packages/zent/src/drawer/components/DrawerContent/index.tsx
> +  const drawerEl = useRef(null);
类型补一下，默认是 any 吧

2020-10-21 06:24 UTC, cpylua commented on packages/zent/src/drawer/components/DrawerContent/index.tsx
> +  const refEventer = useRef<() => void>();
改个名字，`unsubscribePageClickRef` 之类的

2020-10-21 06:25 UTC, cpylua requested changes

2020-10-21 06:25 UTC, cpylua commented on packages/zent/src/drawer/demos/noMask.mdx
> +          e.nativeEvent.stopImmediatePropagation();
这里看下 `stopImmediatePropagation` 是不是可以去掉

2020-10-26 04:03 UTC, merged