[feature] Tabs 新增翻页锚点标签
youzan/zent pull request #1510
Opened 2020-10-26 01:45 UTC by cythiaY

Tabs
- 新增 `overflowMode` 属性，备选值 `'flip'` | `'anchor'`
-`normal` 类型样式统一

2020-10-26 06:56 UTC, cpylua requested changes

2020-10-26 06:56 UTC, cpylua commented on packages/zent/assets/tabs.scss
> +        transition: transform 220ms ease-in-out;
看下 `_timing-functions.scss` 里的定义

2020-10-26 06:56 UTC, cpylua commented on packages/zent/assets/tabs.scss
> +      }
一样的部分可以考虑抽一下

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/README_en-US.md
> +| overflowMode       | support operatains to fit in more tabstabs                                | string                        | `''`       | `'flip'` \| `'anchor'` | no       |
`operatains` 拼错了。

首字母大写

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/operation/AnchorOperation.tsx
> +            <div
外面套了 `ul` 这里嵌 `li` 吧，要么外层也 `div`

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +  }
这函数实现有点绕了，`for` 循环或者 `reduce`

```js
    return tabDataList.reduce((hiddenTabs, tab, idx) => {
        if (i < startIndex && i >= endIndex) {
            hiddenTabs.push(tab);
        }
        return hiddenTabs;
    }, []);
```

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +    return maxTransformIndex;
`maxTransformIndex` 和 `total` 作为一个整体作为 `reduce` 的返回值，类似  `reduce` 的 `state`，这样不依赖外部状态。

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +    }, 0);
`reduce` 的用法同上

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +    });
这里不应该用 `map` 吧

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +  onPageChange(targetIndex: number, disabled = false) {
剪头函数吧，就不需要 `bind` 了。

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +  onAnchorPageChange(tab: IInnerTab<Id>) {
箭头函数

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/types.ts
> +export type ITabOverflowMode = 'flip' | 'anchor';
`flip` → `slide` or `glide`

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/operation/FlipOperation.tsx
> +        onClick={() => onChange(min - 1, disablePrev)}
`useCallback`

2020-10-26 06:56 UTC, cpylua commented on packages/zent/src/tabs/components/operation/FlipOperation.tsx
> +        onClick={() => onChange(min + 1, disableNext)}
`useCallback`

2020-10-26 07:00 UTC, cpylua commented on packages/zent/src/tabs/types.ts
> +export type ITabOverflowMode = 'flip' | 'anchor';
`flip` 是翻转，比如硬币正反两面的翻转；看设计稿这里应该是滑动的意思吧

2020-10-28 15:45 UTC, cythiaY commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +    return maxTransformIndex;
maxTransformIndex 删除

2020-11-01 02:04 UTC, cpylua requested changes

2020-11-01 02:04 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/CommonTabsNav.tsx
> +        {overflowMode && type !== 'button' ? (
这里用白名单吧，安全点 `type !== 'button'`

2020-11-01 02:17 UTC, cpylua requested changes

2020-11-01 02:17 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +  get tabsInfo() {
这换成函数吧，明确使用是有代价的，读宽度太频繁不太好。

2020-11-01 02:17 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +  get tabsInfo() {
下面使用的地方，比如 `onStartChange` 现在代码里是重复调用了多次的，最好优化一下，一个处理流程里只调用一次，子函数里要用可以考虑参数传进去。

2020-11-01 04:42 UTC, cythiaY commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +  }
用户操作后 `startIndex`,  `endIndex` 一定会改变，感觉 `memorize` 的作用不太大
但我还是改了 -_-

2020-11-02 05:07 UTC, cpylua commented on packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
> +  }
触发 `render` 都会调用这个，不去操作 `tabs` 的情况还是挺多的

2020-11-02 05:08 UTC, merged