[new feature] Form: 响应式的校验状态（valid$）
youzan/zent pull request #1530
Opened 2020-11-10 04:45 UTC by wjw99830

2020-11-14 08:00 UTC, cpylua requested changes

2020-11-14 08:01 UTC, cpylua commented
merge 到 `master` 吧，v8 不加这种功能了

2020-11-14 12:32 UTC, wjw99830 commented on packages/zent/src/form/formulr/models/set.ts
> +  private readonly invalidModels: Set<BasicModel<unknown>> = new Set();
如果用`invalidModels: numer`的话，一个`model`连续2次error，会出现2次`invalidModels++`，第三次校验成功，只出现1次`invalidModels--`，会导致校验通过但`valid`仍然为`false`的情况吧

2020-11-14 12:53 UTC, cpylua commented on packages/zent/src/form/formulr/models/set.ts
> +  private readonly invalidModels: Set<BasicModel<unknown>> = new Set();
有道理

2020-11-18 08:10 UTC, cpylua requested changes

2020-11-18 08:10 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +  private unwindChild = (child: Child) => {
改个名字

2020-11-19 07:12 UTC, closed without merging