[new feature] Form: 所有Model对象支持value$、valid$
youzan/zent pull request #1550
Opened 2020-11-19 07:10 UTC by wjw99830

Closes #1527 #1545

2020-11-20 08:31 UTC, cpylua requested changes
顺带把 `empty()` 改成  `EMPTY` 吧。

2020-11-20 08:31 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
>      this.children$.next(nextChildren);
`value$` 没更新

2020-11-20 08:31 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
>      this.children$.next(nextChildren);
漏了 `value$`

2020-11-20 08:31 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +    this.mapModelToSubscriptions.clear();
换成 `_unsubscribeModel`

2020-11-20 08:31 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +        }
else 的情况是一直等到 current 是 model，其他情况忽略？

2020-11-20 08:31 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +    const subs = mapModelToSubscriptions.get(model) || [];
`||` => `??`

2020-11-20 08:31 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +    mapModelToSubscriptions.set(model, [...subs, $]);
`push` 吧

2020-11-20 08:31 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +    this._unsubscribeModel(child);
modelRef `_unsubscribeModel` 做啥

2020-11-21 11:18 UTC, wjw99830 commented on packages/zent/src/form/formulr/models/field.ts
> +    return this.triggerValidate(option).then(maybeError => {
validator执行错误的时候会被`catch`住，对外`reject`，对内`return EMPTY`，`error$`的值不变，这里保持一致的行为吧，内部状态不变，`throw`到外部处理

2020-11-21 11:25 UTC, wjw99830 commented on packages/zent/src/form/formulr/models/set.ts
> +    this.mapModelToSubscriptions.clear();
`_unsubscribeChild`再加了个`invalidModels.delete(model)`，忘了删掉这里的引用

2020-11-21 11:30 UTC, wjw99830 commented on packages/zent/src/form/formulr/models/set.ts
> +      /** 直接使用 getRawValue 便于实现，后续可以优化 value 更新的过程 */
忘了删了，一开始的实现不是这样的

2020-11-21 11:33 UTC, wjw99830 commented on packages/zent/src/form/formulr/models/array.ts
>      this.children$.next(nextChildren);
删除的时候才需要额外`value$.next`一次，`children`的新增和修改都会在`subscribe`里更新`value`

2020-11-21 11:36 UTC, wjw99830 commented on packages/zent/src/form/formulr/models/array.ts
> +        }
需要抛错吗？

2020-11-21 11:37 UTC, wjw99830 commented on packages/zent/src/form/formulr/models/array.ts
> +    this._unsubscribeModel(child);
`modelRef.model$`会被订阅，这里就是为了复用一下取消订阅

2020-11-24 02:52 UTC, cpylua requested changes

2020-11-24 02:52 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +    this.invalidModels.clear();
`_unsubscribeChild` 里做了 delete，这里是否多余？

2020-11-24 02:52 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
>      this.children$.next(nextChildren);
统一处理新增/删除

2020-11-26 12:10 UTC, cpylua requested changes

2020-11-26 12:10 UTC, cpylua commented on packages/zent/src/form/formulr/models/array.ts
> +    });
这里初始值 true 不对吧

2020-11-26 12:10 UTC, cpylua commented on packages/zent/src/form/formulr/models/set.ts
> +    );
增加/删除child更新值也统一处理吧

2020-11-26 12:10 UTC, cpylua commented on packages/zent/src/form/formulr/models/set.ts
> +    }
valid$ 的初始值不对吧

2020-11-26 13:04 UTC, wjw99830 commented on packages/zent/src/form/ZentForm.tsx
> + * @param defaultValue It's **NOT** recommended to set `defaultValue` by operators such as `=` and `??`
不建议使用`const a = useFormValue(form) ?? defaultValue`或者某些用`=`默认赋值的写法

2020-11-27 14:59 UTC, cpylua requested changes

2020-11-27 14:59 UTC, cpylua commented on packages/zent/src/form/formulr/listeners/utils.ts
> +export function useModelFromContext<Model>(
文件名不要叫 utils 吧，就这一个函数，就改成类似函数名的文件名

2020-11-27 14:59 UTC, cpylua commented on packages/zent/src/form/formulr/listeners/field.tsx
> +    } else if (model) {
isModel(model)?

2020-11-27 14:59 UTC, cpylua commented on packages/zent/src/form/demos/19.reactive-valid.md
> +		const $ = form.model.valid$.subscribe(nextValue => {
demo 里换成公开的 API 吧

2020-11-27 14:59 UTC, cpylua commented on packages/zent/src/form/demos/19.reactive-valid.md
> +		const $ = form.model.valid$.subscribe(nextValue => {
相关文档也要补充一下

2020-11-27 14:59 UTC, cpylua commented on packages/zent/src/form/demos/19.reactive-valid.md
> +		const $ = form.model.valid$.subscribe(nextValue => {
`useFieldValid`
`FieldValid`

2020-11-27 15:02 UTC, cpylua commented on packages/zent/src/form/ZentForm.tsx
> + * @param defaultValue It's **NOT** recommended to set `defaultValue` by operators such as `=` and `??`
> It's **NOT** recommended to set `defaultValue` by operators such as `=` and `??`

你要么再表达清楚些？感觉和你那句中文还是差的有点多啊，实在不行写中文也行。

> 不建议使用const a = useFormValue(form) ?? defaultValue或者某些用=默认赋值的写法

这个讲真我还是没懂，不建议的原因是啥？

2020-12-01 07:46 UTC, merged