[bugfix]: DateRangePicker 禁用时间处理修改，并导出类型 `IDisabledTime`
youzan/zent pull request #1589
Opened 2020-12-05 08:02 UTC by cythiaY

### Before submitting a pull request, please make sure the following is done:

### 提交 PR 前请确保完成以下内容:

1. Fork [the repository](https://github.com/youzan/zent) and create your branch from `master`.
2. Follow the [contributing guide](../CONTRIBUTING.md) to setup your develop environment.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Describe your pull request.

### Please remove the above lines when you submit this pull request, also please fill in the changes you've made in this pull request.

### 提交 PR 前 请把以上内容删除，并填写以下内容。

Fixes #xx(issue number here), remove this line if no related issue.

`DateRangePicker`、`CombinedDateRangePicker`:

- 修改 `DisabledTime` 处理逻辑，便于使用方增加额外时间限制
- 修复 `CombinedDateRangePicker` 范围选择端点样式
- 导出类型 `IDisabledTime`

2020-12-05 08:57 UTC, cpylua requested changes

2020-12-05 08:57 UTC, cpylua commented on packages/zent/src/date-picker/demos/disabled-time.md
> +const initRemainArray = (targetNum, total) => {
第一个参数啥意思？

2020-12-05 08:57 UTC, cpylua commented on packages/zent/src/date-picker/demos/disabled-time.md
> +const initRemainArray = (targetNum, total) => {
看着就是 [targetNum+1 ... total] 这么个数组？

那建议写个 range(start, end) 的函数，更直观

2020-12-05 08:57 UTC, cpylua commented on packages/zent/src/date-picker/demos/disabled-time.md
> +			: {};
这个是不是提供一个工具方法能够帮他吃掉这坨，外面所有地方这么用太麻烦了。

2020-12-08 02:07 UTC, youngBrain1893 commented on packages/zent/src/date-picker/disabledTimeFns.ts
> +const initArray = (targetNum: number) => {
感觉这个方法没必要，就是 initRangeArray 默认 start 是 0

2020-12-08 02:11 UTC, youngBrain1893 commented on packages/zent/src/date-picker/README_zh-CN.md
> +- 提供时间禁用的处理方法：`disabledTimeWithMin`、`disabledTimeWithMax` 和 `disabledTimeWithRange`，需要从 `zent/es/date-picker/disabledTimeFns` 引入。
如果确定不再继续支持原来的 `min/max` 我觉得可以直接移除 disabledDate 中 对 `min/max` 的兼容处理

`min/max` 本身升级改动就挺大的了

2020-12-08 02:23 UTC, youngBrain1893 commented on packages/zent/src/date-picker/disabledTimeFns.ts
> +export const disabledTimeWithMin = (
提供统一的方法后，disabledDate 的逻辑应该也在这边处理掉会更合适
现在这种实现方式 min/max 逻辑一部分在 `unifiedDisabledDateFromProps` 里实现，一部分通过这边传入

2020-12-08 02:25 UTC, cythiaY commented on packages/zent/src/date-picker/README_zh-CN.md
> +- 提供时间禁用的处理方法：`disabledTimeWithMin`、`disabledTimeWithMax` 和 `disabledTimeWithRange`，需要从 `zent/es/date-picker/disabledTimeFns` 引入。
这几个方法对时间的作用 约等同于 `min/max` 对日期的作用
本意是为了把日期和时间的处理完全隔离开，才要求分开写

2020-12-08 03:09 UTC, cythiaY commented on packages/zent/src/date-picker/disabledTimeFns.ts
> +const initArray = (targetNum: number) => {
返回值有交集，场景不一样

2020-12-10 09:10 UTC, merged