Grid select support singleSelect
youzan/zent pull request #1645
Opened 2021-01-18 08:56 UTC by youngBrain1893

Changes you made in this pull request:
- Grid 添加 单选支持
- Grid `props.selection` 废弃 `getCheckboxProps` 对应调整为 `getSelectionProps`

2021-01-20 02:32 UTC, youngBrain1893 commented
> 为什么嵌在`span`里面，是这次改动引起的吗 -_-

React 16.x 的某个版本改变了元素 `disabled` 的行为，mouseEnter 不会触发 https://github.com/facebook/react/issues/10109

2021-01-20 03:06 UTC, cpylua commented on packages/zent/src/grid/BatchComponents.tsx
> +        selectionPropsCache[rowIndex] = selection.getCheckboxProps(data);
加个注释说明一下是为了兼容老代码

2021-01-20 03:07 UTC, cpylua commented on packages/zent/src/grid/SelectionCheckbox.tsx
> +        </span>
加 `<span>`  干啥

2021-01-20 03:08 UTC, cpylua commented on packages/zent/src/grid/demos/selection.md
> +	title: 单选
这是多选吧

2021-01-20 03:10 UTC, cpylua commented on packages/zent/src/grid/types.ts
> +  // @depreciate use getSelectionProps
deprecated 拼错了

2021-01-20 03:15 UTC, cpylua commented on packages/zent/src/grid/SelectionRadio.tsx
> +    }
`this.unsubscribe?.()`

2021-01-20 03:16 UTC, cpylua commented on packages/zent/src/grid/SelectionRadio.tsx
> +    return reason && disabled ? (
没有 `reason` 不能 `disable` 吗？

2021-01-20 03:17 UTC, cpylua commented on packages/zent/src/grid/SelectionRadio.tsx
> +        </span>
`span` 是为啥

2021-01-20 03:21 UTC, cpylua commented on packages/zent/src/grid/Grid.tsx
> +    if (hasLeft && selectionColumn) {
`selectionColumn` 这判断多余的吧

2021-01-20 03:23 UTC, cpylua commented on packages/zent/src/grid/Grid.tsx
> +      }
加个注释

2021-01-20 03:26 UTC, cpylua commented on packages/zent/src/grid/Grid.tsx
> +        >
为啥要包一层

2021-01-20 03:26 UTC, cpylua requested changes
再改下

2021-01-20 06:16 UTC, youngBrain1893 commented on packages/zent/src/grid/BatchComponents.tsx
> +        selectionPropsCache[rowIndex] = selection.getCheckboxProps(data);
done

2021-01-20 06:18 UTC, youngBrain1893 commented on packages/zent/src/grid/SelectionCheckbox.tsx
> +        </span>
disabled 元素 React 不会触发 mouse 相关事件，Pop 不生效，导致 `reason` 功能未生效
facebook/react#10109

2021-01-20 06:19 UTC, youngBrain1893 commented on packages/zent/src/grid/demos/selection.md
> +	title: 单选
done

2021-01-20 06:19 UTC, youngBrain1893 commented on packages/zent/src/grid/Grid.tsx
> +    if (hasLeft && selectionColumn) {
done

2021-01-20 06:36 UTC, youngBrain1893 commented on packages/zent/src/grid/Grid.tsx
> +        >
与 checkbox 保持一致，之前应该是想能够做样式覆盖
单选 className 调整为 `zent-grid-selection-radio` 了

2021-01-21 02:04 UTC, cpylua requested changes

2021-01-21 02:04 UTC, cpylua commented on packages/zent/src/grid/SelectionRadio.tsx
> +  }
不要用 willReceiveProps

2021-01-21 11:38 UTC, merged