[feature]: Affix add  prop to set relative-position node
youzan/zent pull request #1685
Opened 2021-04-01 07:05 UTC by cythiaY

Affix:

- 增加属性 `target` 用于自定义设置固钉相对定位的节点，默认为 window

2021-04-01 13:03 UTC, cpylua requested changes

2021-04-01 13:03 UTC, cpylua commented on packages/zent/src/affix/Affix.tsx
> +      <WindowScrollHandler onScroll={onWindowSrcoll} />
看下 `useResizeObserver`，大小变化也会导致位置变化。

2021-04-02 08:34 UTC, cythiaY commented on packages/zent/src/affix/Affix.tsx
> +      <WindowScrollHandler onScroll={onWindowSrcoll} />
`target` 的改变作用在占位符上，`observer` 监听占位符的大小变化，所以不需要再次监听 `target` 的 `resize`
该场景已自测通过

2021-04-08 09:34 UTC, cpylua requested changes

2021-04-08 09:34 UTC, cpylua commented on packages/zent/src/affix/Affix.tsx
> +interface IAffixImperativeHandlers {
这里export出去

2021-04-08 09:34 UTC, cpylua commented on packages/zent/src/affix/Affix.tsx
> +  affixRef?: React.RefObject<IAffixImperativeHandlers>;
可以直接用 `forwardRef`

2021-04-16 07:51 UTC, merged