Feature: 更新语义化形式，支持主题动态切换
youzan/zent pull request #1712
Opened 2021-06-15 03:38 UTC by maiijy

1. 更换语义化的使用形式和标准，增加动态切换的能力，提供sdk
2. 所有的focus的主题色阴影去除，只提供中性色的阴影
3. button组件只保留primary和default两种种类

2021-06-15 12:53 UTC, cpylua commented on packages/zent/package.json
> +    "@ctrl/tinycolor": "^3.4.0",
src/utils/tinycolor 有个精简版，看看够不够用。

2021-06-16 02:46 UTC, cpylua commented on packages/zent/assets/notice.scss
> -    overflow-y: hidden;
这个为啥删了

2021-06-16 02:46 UTC, cpylua commented on packages/zent/assets/select.scss
> -    @include theme-shadow(focus);
这些阴影都是设计要求删掉的吗？

2021-06-16 02:53 UTC, cpylua commented on packages/zent/src/color/theme-ref.ts
> +export const themeRefs = {
这个文件加个注释头说明是生成的

2021-06-16 02:56 UTC, cpylua commented on site/src/components/theme-change-trigger/index.js
> +  const content = () => {
套一层做啥？直接用 `BlockPicker` 不行吗

2021-06-16 02:59 UTC, cpylua commented on site/src/components/theme-change-trigger/index.js
> +export default function ThemeGenerator({
`ThemeSwitcher`，文件名也改下

2021-06-16 03:02 UTC, cpylua commented on site/src/components/theme-change-trigger/index.js
> +export default function ThemeGenerator({
还有 className，和组件名字对应起来。

2021-06-16 03:06 UTC, cpylua commented on site/webpack/webpack.config.js
> +            use: 'raw-loader',
Markdown 渲染用统一的，不要单独搞，有些交互处理会有差异。

看下 `react-template.jstpl`，单独弄个模版重写一下 `Demo` 块的实现就行了。

然后通过 `<!-- demo-slot-1 -->` 控制插入位置，看下 form 的文档。

2021-06-16 03:10 UTC, cpylua commented on site/src/components/theme-change-trigger/index.js
> +  onlyTrigger = false,
`noColorDetails` 明确去掉什么东西

2021-06-16 03:11 UTC, cpylua commented on site/webpack/webpack.config.js
> +            use: 'raw-loader',
`zent/src/color` => `zent/src/theme` 然后按正常组件的文档书写方式组织

2021-06-16 03:13 UTC, cpylua commented on packages/zent/src/color/theme-ref.ts
> +export const themeRefs = {
这个文件要加个注释，看不懂每项是什么意思

2021-06-16 03:14 UTC, cpylua commented on packages/zent/package.json
> +    "var": "./scripts/postcss-vars.sh"
`var` 这个名字太简单了吧

2021-06-16 03:19 UTC, cpylua commented on packages/zent/assets/theme/_old-default.scss
> +  );
你优先级是不是都写反了？应该新的在前，老的在后吧？

2021-06-16 03:20 UTC, cpylua commented on packages/zent/assets/theme/variables/_raw-vars.scss
> +@import '../color-generator';
variables 每个文件加个注释，有点多，搞不清楚干什么用的了

2021-06-16 03:21 UTC, cpylua commented on packages/zent/assets/theme/_default.scss
> +  $style: solid,
为什么都要换个新名字，直接用老的不行吗？存在两套很奇怪。

2021-06-16 03:22 UTC, cpylua commented on packages/zent/assets/theme/_default.scss
> +  $style: solid,
我觉得实现就应该只有一个，只不过是兼容老的css变量。

2021-06-16 03:25 UTC, cpylua commented on packages/zent/assets/theme/_default.scss
> +$null: 'NULL';
这个变量很奇怪啊。。。为什么会需要这么一个值

2021-06-16 03:28 UTC, cpylua commented on packages/zent/assets/theme/_default.scss
> +@function zent-color-var-rgba($type, $desc: $null, $opacity: 1) {
type 和 desc 是啥意思？原来的 $cat 和 $i 用法很简单，看一眼就知道是啥意思，新的不太明白。

2021-06-16 03:29 UTC, cpylua commented on packages/zent/assets/button.scss
> +      @include zent-color(border-left-color, section, bg);
跟下面说的一样，不应该有套 mixin

2021-06-16 03:29 UTC, cpylua commented on packages/zent/assets/button.scss
> +      @include zent-color(border-bottom-color, section, bg);
跟下面说的一样，不应该有套 mixin

2021-06-16 03:30 UTC, cpylua requested changes
问题有点多，先看下。

2021-06-16 03:30 UTC, cpylua commented on packages/zent/assets/colorpicker.scss
> -      @include theme-shadow(focus);
设计要求删的吗？

2021-06-16 03:31 UTC, cpylua commented on yarn.lock
> +"@ctrl/tinycolor@^3.4.0":
不要用内网源

2021-06-16 03:31 UTC, cpylua requested changes
CI 除了源的问题再看下还有没有问题，CI 要过的。

2021-06-16 03:31 UTC, cpylua commented on yarn.lock
> +"@ctrl/tinycolor@^3.4.0":
revert 掉，重新装一下

2021-06-17 03:41 UTC, maiijy commented on packages/zent/assets/colorpicker.scss
> -      @include theme-shadow(focus);
是的，主题色的阴影不再提供

2021-06-17 09:56 UTC, maiijy commented on packages/zent/assets/theme/_default.scss
> +@function zent-color-var-rgba($type, $desc: $null, $opacity: 1) {
现在改为$cat,和$attr

2021-06-17 09:58 UTC, maiijy commented on packages/zent/assets/notice.scss
> -    overflow-y: hidden;
阴影的边距变大了，之前预留的margin不够的情况下，阴影会被截断。

2021-06-18 06:56 UTC, cpylua requested changes

2021-06-18 06:56 UTC, cpylua commented on packages/zent/src/theme/index.ts
> +export * from './generator';
这个没必要在这里导出去吧

2021-06-18 06:56 UTC, cpylua commented on packages/zent/src/theme/generator.ts
> +export function generate(hex: string): string[] {
这个函数是生成色板吗？换个名字 generatePalette

2021-06-18 06:56 UTC, cpylua commented on packages/zent/assets/theme/variables/_text.scss
> +$font-size-h1: 44px;
这个为什么在这里写死的？

2021-06-18 06:56 UTC, cpylua commented on packages/zent/src/theme/sdk.ts
> +interface IExtraThemeInfo {
IThemeExtraInfo

2021-06-18 06:56 UTC, cpylua commented on packages/zent/src/theme/sdk.ts
> +  getAllThemeColor: (hex: string) => IThemeAllItem[];
为什么 getAllThemeColor 和 getThemeColor 参数和返回值都不一样的？是不是换个名字。

2021-06-18 06:56 UTC, cpylua commented on packages/zent/src/theme/sdk.ts
> +  setAllThemeColor: (hex: string) => void;
这些函数都写下注释，干什么的。中文 
相关的函数放一起。

2021-06-18 06:56 UTC, cpylua commented on packages/zent/src/theme/sdk.ts
> +export const ThemeSdk: IThemeSdk = {
我觉得你还不如写个 class 然后挂 static 方法，代码看起来有点累。

2021-06-18 06:56 UTC, cpylua commented on packages/zent/src/theme/sdk.ts
> +  setAllThemeColor: (hex: string) => void;
生成，获取，设置

2021-06-18 06:56 UTC, cpylua commented on packages/zent/assets/theme/_default.scss
> +@mixin theme-shadow($cat) {
这个文件现在很大，把 export 出去给人用的 mixin 放一起，代码分一下块，东西多了看着很乱，导出什么也不明确。

2021-06-18 06:56 UTC, cpylua commented on packages/zent/assets/theme/_color-generator.scss
> +@function getLightSaturation($h, $s, $v, $level) {
这个文件里的函数没见你用过，还是我看漏了

2021-06-18 06:56 UTC, cpylua commented on packages/zent/assets/theme/_override.scss
> +// Use this file to override variables in _default.scss, includes old or new
variables/ 目录下好多新加的变量都无法被 _override 覆盖，故意的还是漏了？

2021-06-18 06:56 UTC, cpylua commented on packages/zent/assets/theme/_override.scss
> +// Use this file to override variables in _default.scss, includes old or new
比如字体大小

2021-06-20 02:17 UTC, maiijy commented on packages/zent/assets/grid.scss
> +    @include theme-shadow(focus);
设计要求的，验收过

2021-06-21 02:07 UTC, maiijy commented on packages/zent/src/button/demos/loading.md
> -			</Button>
只是在demo上删除了示例

2021-06-21 02:08 UTC, maiijy commented on packages/zent/assets/theme/variables/_text.scss
> +$font-size-h1: 44px;
老版的字体大小，新版不存在映射，就保留了老版的值

2021-06-23 03:17 UTC, closed without merging

2021-06-23 03:18 UTC, cpylua commented
Duplicate of #1714