fix: 当select初始化样式display为none，再显示时triggerWidth为0
youzan/zent pull request #1727
Opened 2021-07-05 03:44 UTC by unStone

fix: 当select初始化样式display为none，再显示时triggerWidth为0

2021-07-05 06:14 UTC, cpylua commented on packages/zent/src/select/Select.tsx
> +      this.triggerRef.current?.offsetWidth || this.props.width;
判断一下 `width` 是不是数字，百分比给 popup 设置上去会出问题的。

2021-07-05 06:14 UTC, cpylua requested changes

2021-07-05 06:14 UTC, cpylua commented on packages/zent/src/select/Select.tsx
> +      this.triggerRef.current?.offsetWidth || this.props.width;
判断一下 width 是不是数字，百分比给 popup 设置上去会出问题的。

2021-07-06 02:17 UTC, cythiaY commented on packages/zent/src/select/Select.tsx
> +        : DEFAULT_TRIGGER_WIDTH;
问题的根本是给 `triggerWidth` 赋值的时机不准确，感觉直接用默认值处理，计算的逻辑就跟之前不太一致

2021-07-06 02:26 UTC, cpylua commented on packages/zent/src/select/Select.tsx
> +        : DEFAULT_TRIGGER_WIDTH;
最开始的逻辑是 `popupWidth = popupWidth ?? width`，跟现在本质上是一样的，现在就是处理了一下百分比这种宽度的场景。

出问题的场景是 `mount` 时候组件是被外部隐藏的，所以拿不到宽度。我觉得这种用法一不多见，二有点奇怪，所以没必要为了这一个场景弄的特别复杂。

2021-07-06 15:37 UTC, merged