移除按钮的danger/success/waring类型的hover/active状态
youzan/zent pull request #1798
Opened 2021-09-23 03:16 UTC by maiijy

1. 去除 Button 中 danger/success/waring 类型的文档显示，保留已使用的场景代码
2. 已使用的场景不区分hover/active的状态颜色变化，警示色不存在状态区分

2021-09-26 03:19 UTC, cpylua commented
全局搜一下 type="danger"/"success" 没改全。

2021-09-26 13:47 UTC, cpylua requested changes

2021-09-26 13:47 UTC, cpylua commented on packages/zent/src/sweetalert/demos/button-type.md
> +			confirmType: 'primary',
默认就是 primary 例子的话换一个值吧。

2021-09-27 03:42 UTC, maiijy commented on packages/zent/src/split-button/demos/dropdown-position.md
> -				<SplitButton
还原，提成为"primary"类型

2021-09-27 03:43 UTC, maiijy commented on packages/zent/src/sweetalert/demos/button-type.md
> +			confirmType: 'primary',
button默认值是"default"，所以这里换成"primary"

2021-09-27 07:15 UTC, merged