feat: [Cascader] 新增 simplifySelectionMode
youzan/zent pull request #1928
Opened 2022-03-03 12:33 UTC by goo-yyh

- `cascader`
  - ✨ 增加`simplifySelectionMode`判断`simplifySelection`时是否包含`disabled`的路径

2022-03-03 12:42 UTC, w91 commented on packages/zent/src/cascader/demos/14.simplify.md
> +						simplifySelectionMode="all"
这个是不是漏改了

2022-03-08 02:47 UTC, cpylua requested changes

2022-03-08 02:47 UTC, cpylua commented on packages/zent/src/cascader/MenuCascader.tsx
> +  private getSimplifySelectionMap = memorizeOne(
getSelectionMap 还有别的地方在用吧？这样子不同地方的处理逻辑会对不上了

2022-03-08 02:52 UTC, goo-yyh commented on packages/zent/src/cascader/MenuCascader.tsx
> +  private getSimplifySelectionMap = memorizeOne(
> getSelectionMap 还有别的地方在用吧？这样子不同地方的处理逻辑会对不上了

其他地方的逻辑和原来保持不变，其实就只改变simplify下，tags显示的结果。

2022-03-08 02:53 UTC, goo-yyh commented on packages/zent/src/cascader/MenuCascader.tsx
> +  private getSimplifySelectionMap = memorizeOne(
> > getSelectionMap 还有别的地方在用吧？这样子不同地方的处理逻辑会对不上了
> 
> 其他地方的逻辑和原来保持不变，其实就只改变simplify下，tags显示的结果。

原来用到`getSelectionMap`还是用之前的函数，新增了一个多了mode参数的方法，去计算tags中显示的simplifyPath

2022-03-08 10:58 UTC, cpylua commented on packages/zent/src/cascader/MenuCascader.tsx
> +  private getSimplifySelectionMap = memorizeOne(
这些地方逻辑不一致不会有问题吗？

2022-03-10 09:00 UTC, merged